algoritmo "grupo 1 - 2"
// Função :
// Autor :
// Data : 24/05/2021
// Seção de Declarações 
var
cont, N1, N2 : inteiro
inicio
Escreval ("Digite um número inteiro quando for solicitado, o primeiro deve ser menor que o seguundo.")
escreval ("Digite o primeiro número:")
leia (n1)
escreval ("Digite o segundo número:")
leia (n2)
cont <-  n1
enquanto cont < n2 faca
escreva (cont,"-")
cont <- cont + 1
fimenquanto
// Seção de Comandos 
fimalgoritmo
